version: '3.8'

networks:
  picthor-local:

services:
  database:
    image: 'postgres:latest'
    container_name: 'picthor-postgres'
    networks:
      - picthor-local

  picthorio:
    image: picthorio/picthor-io:latest
    container_name: 'picthor-app'
    networks:
      - picthor-local
    environment:
      PICTHOR_UI_STATIC_FILES_DIR: /root/picthor-io-ui-dist
      PICTHOR_CACHE_DIR: /root/pichtor-cache
    depends_on:
      - database


